const MANAGER_DOES_NOT_EXISTS_ERROR = require('./MANAGER_DOES_NOT_EXISTS_ERROR');
const DUPLICATE_MOBILE_ERROR = require('./DUPLICATE_MOBILE_ERROR');
const MOBILE_CANT_UPDATE = require('./MOBILE_CANT_UPDATE');
const INPUT_FORMAT_ERROR = require('./INPUT_FORMAT_ERROR');
const EMPLOYEE_DOES_NOT_EXIST = require('./EMPLOYEE_DOES_NOT_EXIST');
const EMPLOYEE_ALREADY_EXIST = require('./EMPLOYEE_ALREADY_EXIST');
const UNAUTHORIZED_ACCESS = require('./UNAUTHORIZED_ACCESS');
const DATA_BASE_ERROR = require('./DATA_BASE_ERROR');
const SCHEMA_VALIDATION_ERROR=require('./SCHEMA_VALIDATION_ERROR');
const YOU_CANT_CREATE_EMPLOYEE=require('./YOU_CANT_CREATE_EMPLOYEE');
const EMPLOYEE_NOT_HAVE_ORGANIZATION=require('./EMPLOYEE_NOT_HAVE_ORGANIZATION');
const INVALID_MANAGER=require('./INVALID_MANAGER');

module.exports = {
  MANAGER_DOES_NOT_EXISTS_ERROR,
  DUPLICATE_MOBILE_ERROR,
  INPUT_FORMAT_ERROR,
  EMPLOYEE_DOES_NOT_EXIST,
  EMPLOYEE_ALREADY_EXIST,
  UNAUTHORIZED_ACCESS,
  DATA_BASE_ERROR,
  MOBILE_CANT_UPDATE,
  SCHEMA_VALIDATION_ERROR,
  YOU_CANT_CREATE_EMPLOYEE,
  EMPLOYEE_NOT_HAVE_ORGANIZATION,
  INVALID_MANAGER
};
