const INDIVIDUAL = {
  INDIVIDUAL: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    signup: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    profile_completion: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 20,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  RETAILER: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  LOGISTICS_DELIVERY: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
};

const RETAILER = {
  INDIVIDUAL: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    signup: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    profile_completion: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 20,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  RETAILER: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  LOGISTICS_DELIVERY: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
};

const EMPLOYEE_SSO = {
  INDIVIDUAL: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    signup: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    profile_completion: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 20,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  RETAILER: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  LOGISTICS_DELIVERY: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
};

const EMPLOYEE_SH = {
  INDIVIDUAL: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    signup: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    profile_completion: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 20,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  RETAILER: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  LOGISTICS_DELIVERY: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
};

const EMPLOYEE_CO = {
  INDIVIDUAL: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    signup: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    profile_completion: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 20,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  RETAILER: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  LOGISTICS_DELIVERY: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
};

const LOGISTICS_DELIVERY = {
  INDIVIDUAL: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    signup: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    profile_completion: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 20,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  RETAILER: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
  LOGISTICS_DELIVERY: {
    ack: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    referral_reward: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    kyc: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: false,
      rewardAmount: 0,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
    buy_subscription: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 70,
      cashback: true,
      cashbackAmount: 499,
      status: false,
      updatedAt: new Date(),
    },
    order_completed: {
      priority: 1,
      optional: true,
      rewardType: "WALLET",
      reward: true,
      rewardAmount: 50,
      cashback: false,
      cashbackAmount: 0,
      status: false,
      updatedAt: new Date(),
    },
  },
};

module.exports = {
  INDIVIDUAL,
  RETAILER,
  EMPLOYEE_SSO,
  EMPLOYEE_SH,
  EMPLOYEE_CO,
  LOGISTICS_DELIVERY,
};
