version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginxserver
    restart: unless-stopped
    # network_mode: host
    ports:
      - 80:8080
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
