const SELF_INVITE_ERROR = require("./SELF_INVITE_ERROR");
const ALREADY_REGISTERED_USER_ERROR = require("./ALREADY_REGISTERED_USER_ERROR");
const UMS_API_CALL_ERROR = require("./UMS_API_CALL_ERROR");
const INVITE_LIMIT_REACHED_ERROR = require("./INVITE_LIMIT_REACHED_ERROR");
const APPNAME_UNDEFINED_ERROR = require("./APPNAME_UNDEFINED_ERROR");
const DUPLICATE_KEY_ERROR = require("./DUPLICATE_KEY_ERROR");
const SEND_INVITE_ERROR = require("./SEND_INVITE_ERROR");
const REMINDER_LIMIT_REACHED_ERROR = require("./REMINDER_LIMIT_REACHED_ERROR");
const SEND_REMINDER_ERROR = require("./SEND_REMINDER_ERROR");
const REMINDER_COUNT_UPDATE_ERROR = require("./REMINDER_COUNT_UPDATE_ERROR");
const REMINDER_COUNT_READ_ERROR = require("./REMINDER_COUNT_READ_ERROR");
const REFERRAL_UPDATE_ERROR = require("./REFERRAL_UPDATE_ERROR");
const REFERRAL_READ_ERROR = require("./REFERRAL_READ_ERROR");
const ACTIVE_REF_STATUS_ERROR = require("./ACTIVE_REF_STATUS_ERROR");
const REFERRAL_STATUS_UPDATE_ERROR = require("./REFERRAL_STATUS_UPDATE_ERROR");
const STORY_READ_ERROR = require("./STORY_READ_ERROR");
const REWARD_READ_ERROR = require("./REWARD_READ_ERROR");
const DUPLICATE_ORDER_ID_ERROR = require("./DUPLICATE_ORDER_ID_ERROR");
const REWARDS_COULD_NOT_BE_ADDED = require("./REWARDS_COULD_NOT_BE_ADDED");
const DATABASE_CONNECTION_ERROR = require("./DATABASE_CONNECTION_ERROR");
module.exports = {
  SELF_INVITE_ERROR,
  ALREADY_REGISTERED_USER_ERROR,
  UMS_API_CALL_ERROR,
  APPNAME_UNDEFINED_ERROR,
  INVITE_LIMIT_REACHED_ERROR,
  DUPLICATE_KEY_ERROR,
  SEND_INVITE_ERROR,
  REMINDER_LIMIT_REACHED_ERROR,
  SEND_REMINDER_ERROR,
  REMINDER_COUNT_UPDATE_ERROR,
  REMINDER_COUNT_READ_ERROR,
  REFERRAL_UPDATE_ERROR,
  REFERRAL_READ_ERROR,
  ACTIVE_REF_STATUS_ERROR,
  REFERRAL_STATUS_UPDATE_ERROR,
  STORY_READ_ERROR,
  REWARD_READ_ERROR,
  DUPLICATE_ORDER_ID_ERROR,
  REWARDS_COULD_NOT_BE_ADDED,
  DATABASE_CONNECTION_ERROR,
};
