const DATA_BASE_ERROR = require('./DATA_BASE_ERROR');
const DATABASE_CONNECTION_ERROR = require('./DATABASE_CONNECTION_ERROR');
const ERROR_UPLOADING_DATA = require('./ERROR_UPLOADING_DATA');
const VALIDATION_ERROR = require('./VALIDATION_ERROR');
const INTERNAL_SERVER_ERROR = require('./INTERNAL_SERVER_ERROR');

module.exports = {
  DATA_BASE_ERROR,
  DATABASE_CONNECTION_ERROR,
  ERROR_UPLOADING_DATA,
  VALIDATION_ERROR,
  INTERNAL_SERVER_ERROR,
};
