const STATUS = {
    NEW: 'NEW',
    ACCEPTED: 'ACCEPTED',
    PROCESSING: 'PROCESSING',
    READY: 'READY',
    DISPATCHED: 'DISPATCHED',
    DELIVER: 'DELIVER',
    DELIVERY: 'DELIVERY',
    PICKEDUP: 'PICKEDUP',
    IN_TRANSIT: 'IN_TRANSIT',
    // RECHED_DELIVERY_LOCATION: 'RECHED_DELIVERY_LOCATION',
    REACHED_DELIVERY_LOCATION: 'REACHED_DELIVERY_LOCATION',
    PICKUP: 'PICKUP',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED',
    DELIVERED: 'DELIVERED',
    COMPLETED: 'COMPLETED',
    NO_SHOW: 'NO_SHOW',
    PAYMENT_PENDING: "PAYMENT_PENDING",
    REACHED_DL: "REACHED_DL"
};
module.exports = { STATUS };
