const SEND_OTP_ERROR = require('./SEND_OTP_ERROR');
const VERIFY_OTP_ERROR = require('./VERIFY_OTP_ERROR');
const OTP_NOT_MATCHED_ERROR = require('./OTP_NOT_MATCHED_ERROR');
const OTP_NOT_FOUND_IN_DB_ERROR = require('./OTP_NOT_FOUND_IN_DB_ERROR');
const DB_CONNECTION_ERROR = require('./DB_CONNECTION_ERROR');
const NULL_OTP_ERROR = require('./NULL_OTP_ERROR');
const RETRY_LIMIT_EXCEEDED_ERROR = require('./RETRY_LIMIT_EXCEEDED_ERROR');
const RETRY_OTP_ERROR = require('./RETRY_OTP_ERROR');

module.exports = {
  SEND_OTP_ERROR,
  VERIFY_OTP_ERROR,
  OTP_NOT_MATCHED_ERROR,
  OTP_NOT_FOUND_IN_DB_ERROR,
  DB_CONNECTION_ERROR,
  NULL_OTP_ERROR,
  RETRY_LIMIT_EXCEEDED_ERROR,
  RETRY_OTP_ERROR,
};
